version: 2

sources:
  - name: stripe
    database: dbt-tutorial
    schema: stripe
    tables:
      - name: payment
  - name: jaffle_shop
    description: a clone of a Postgres application database
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
        description: the raw customers data
        columns:
          - name: id
            description: the primary key for the raw customers data
            tests:
            - unique
            - not_null
      - name: orders
        description: the raw orders data 
        columns:
          - name: id
            description: the primary key for the raw orders data
            tests:
            - unique
            - not_null
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}


models:
  - name: customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key for customers
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: stg_customers
    description: This model cleans up customer data (one unique customer per row)
    columns:
      - name: customer_id
        description: Primary key for stg_customers
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up order data (one order per customer)
    columns:
      - name: order_id
        description: Primary key for stg_orders
        tests:
          - unique
          - not_null
      - name: status
        description: '{{ doc("order_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: stg_payments.sql
    description: This model cleans up payment data
